class_name AtelierStrings
extends RefCounted

## Chaves de localização compartilhadas pela interface.
##
## Os textos ficam em `res://localization/ui.csv`. Manter as chaves aqui
## evita espalhar literais pelos painéis e dá aos controles nomes acessíveis,
## tooltips e rótulos que podem ser traduzidos pelo mesmo catálogo.

# Painel do grimório / lista de comandos.
const COMMANDS_TITLE := &"UI_COMMANDS_TITLE"
const COMMANDS_SUBTITLE := &"UI_COMMANDS_SUBTITLE"
const COMMANDS_EMPTY := &"UI_COMMANDS_EMPTY"
const GRIMOIRE_TITLE := &"UI_GRIMOIRE_TITLE"
const GRIMOIRE_SUBTITLE := &"UI_GRIMOIRE_SUBTITLE"
const GRIMOIRE_ACCESSIBLE_DESCRIPTION := &"UI_GRIMOIRE_ACCESSIBLE_DESCRIPTION"
const GRIMOIRE_LIST := &"UI_GRIMOIRE_LIST"

# Paleta de selos e barra de execução.
const PALETTE_COLLAPSED_TITLE := &"UI_PALETTE_COLLAPSED_TITLE"
const PALETTE_TITLE := &"UI_PALETTE_TITLE"
const PALETTE_SUBTITLE := &"UI_PALETTE_SUBTITLE"
const PALETTE_ACCESSIBLE_DESCRIPTION := &"UI_PALETTE_ACCESSIBLE_DESCRIPTION"
const PALETTE_LIST := &"UI_PALETTE_LIST"
const MORE_CONTROLS := &"UI_MORE_CONTROLS"
const EXECUTION_SPEED := &"UI_EXECUTION_SPEED"

# Saída da execução.
const EXECUTION_COLLAPSED_TITLE := &"UI_EXECUTION_COLLAPSED_TITLE"
const EXECUTION_TITLE := &"UI_EXECUTION_TITLE"
const EXECUTION_SUBTITLE := &"UI_EXECUTION_SUBTITLE"
const OUTPUT_TITLE := &"UI_OUTPUT_TITLE"
const ERRORS_TITLE := &"UI_ERRORS_TITLE"
const EXECUTION_EMPTY := &"UI_EXECUTION_EMPTY"
const EXECUTION_INTERRUPTED := &"UI_EXECUTION_INTERRUPTED"
const EXECUTION_DESCRIPTION := &"UI_EXECUTION_DESCRIPTION"
const EXECUTION_OUTPUT := &"UI_EXECUTION_OUTPUT"
const EXECUTION_DIAGNOSTICS := &"UI_EXECUTION_DIAGNOSTICS"
const EXECUTION_OUTPUT_EMPTY := &"UI_EXECUTION_OUTPUT_EMPTY"
const EXECUTION_DIAGNOSTICS_EMPTY := &"UI_EXECUTION_DIAGNOSTICS_EMPTY"
const EXECUTION_PANEL_ACCESSIBLE := &"UI_EXECUTION_PANEL_A11Y"
const EXECUTION_OUTPUT_ACCESSIBLE := &"UI_EXECUTION_OUTPUT_A11Y"
const EXECUTION_DIAGNOSTICS_ACCESSIBLE := &"UI_EXECUTION_DIAGNOSTICS_A11Y"
const EXECUTION_COLLAPSE := &"UI_EXECUTION_COLLAPSE"
const EXECUTION_EXPAND := &"UI_EXECUTION_EXPAND"

# Pilha.
const STACK_TITLE := &"UI_STACK_TITLE"
const STACK_SUBTITLE := &"UI_STACK_SUBTITLE"
const STACK_TOP := &"UI_STACK_TOP"
const STACK_COUNT := &"UI_STACK_COUNT"
const STACK_HIDDEN_COUNT := &"UI_STACK_HIDDEN_COUNT"
const STACK_IDLE_LINE_1 := &"UI_STACK_IDLE_LINE_1"
const STACK_IDLE_LINE_2 := &"UI_STACK_IDLE_LINE_2"
const STACK_EMPTY := &"UI_STACK_EMPTY"
const STACK_ACCESSIBLE_DESCRIPTION := &"UI_STACK_ACCESSIBLE_DESCRIPTION"
const STACK_LIST := &"UI_STACK_LIST"
const STACK_TOP_PREFIX := &"UI_STACK_TOP_PREFIX"
const STACK_ACCESSIBLE_CONTENT := &"UI_STACK_ACCESSIBLE_CONTENT"

# Inspetor de intensidade.
const INTENSITY_TITLE := &"UI_INTENSITY_TITLE"
const INTENSITY_VALUE_ACCESSIBLE := &"UI_INTENSITY_VALUE_ACCESSIBLE"
const INTENSITY_SLIDER_ACCESSIBLE := &"UI_INTENSITY_SLIDER_ACCESSIBLE"

# Botões e nomes acessíveis.
const BUTTON_PLAY := &"UI_BUTTON_PLAY"
const BUTTON_PAUSE := &"UI_BUTTON_PAUSE"
const BUTTON_STEP := &"UI_BUTTON_STEP"
const BUTTON_STOP := &"UI_BUTTON_STOP"
const BUTTON_LIGHT_THEME := &"UI_BUTTON_LIGHT_THEME"
const BUTTON_DARK_THEME := &"UI_BUTTON_DARK_THEME"
const BUTTON_EXPAND := &"UI_BUTTON_EXPAND"
const BUTTON_COLLAPSE := &"UI_BUTTON_COLLAPSE"
const PLAY := &"UI_PLAY"
const PAUSE := &"UI_PAUSE"
const STEP := &"UI_STEP"
const STOP := &"UI_STOP"
const THEME_TOGGLE := &"UI_THEME_TOGGLE"
const PANEL_EXPAND := &"UI_PANEL_EXPAND"
const PANEL_COLLAPSE := &"UI_PANEL_COLLAPSE"

# Tooltips dos controles.
const TOOLTIP_PLAY := &"UI_TOOLTIP_PLAY"
const TOOLTIP_PAUSE := &"UI_TOOLTIP_PAUSE"
const TOOLTIP_STEP := &"UI_TOOLTIP_STEP"
const TOOLTIP_STOP := &"UI_TOOLTIP_STOP"
const TOOLTIP_LIGHT_THEME := &"UI_TOOLTIP_LIGHT_THEME"
const TOOLTIP_DARK_THEME := &"UI_TOOLTIP_DARK_THEME"
const TOOLTIP_EXPAND := &"UI_TOOLTIP_EXPAND"
const TOOLTIP_COLLAPSE := &"UI_TOOLTIP_COLLAPSE"
const TOOLTIP_EXECUTION_SPEED := &"UI_TOOLTIP_EXECUTION_SPEED"
const TOOLTIP_INTENSITY := &"UI_TOOLTIP_INTENSITY"
const PLAY_DESCRIPTION := &"UI_PLAY_DESCRIPTION"
const RESUME_DESCRIPTION := &"UI_RESUME_DESCRIPTION"

# Diagnóstico de desempenho.
const DIAGNOSTICS_TITLE := &"UI_DIAGNOSTICS_TITLE"
const DIAGNOSTICS_FPS := &"UI_DIAGNOSTICS_FPS"
const DIAGNOSTICS_STAGES := &"UI_DIAGNOSTICS_STAGES"
const DIAGNOSTICS_CELLS := &"UI_DIAGNOSTICS_CELLS"
const DIAGNOSTICS_GRID := &"UI_DIAGNOSTICS_GRID"


static func text(key: StringName) -> String:
	return TranslationServer.translate(str(key))


static func format(key: StringName, values: Array) -> String:
	return text(key) % values
